### ISSUE TITLE
level=fatal msg="crowdsec init: while loading acquisition config: no datasource enabled"

### ISSUE THREAD

**Issue by bbigras** [kampka/nix-flake-crowdsec#3]
How can I monitor the sshd journald log?

**Comment by bbigras** [comment]
I needed:

- #1.
- an acquis.yml file
- `services.crowdsec.settings.crowdsec_service.acquisition_path = "my_acquis_file.yml";`
- run `cscli collections install crowdsecurity/linux` once

acquis.yml
```yaml
source: journalctl
journalctl_filter:
 - "_SYSTEMD_UNIT=sshd.service"
labels:
  type: syslog
```

---

Should we rename this issue to "Feature request: automatic sshd config"?
